contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mtbseq channel"
    url: https://nfcore.slack.com/channels/mtbseq
    about: Discussion about the nf-core/mtbseq pipeline
